id: A6C360E5C
title: Short Prayer to Atiśa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:11:47.477108
  last_modified_at: 2022-03-01 02:11:47.477111
