id: A6C360E5C
title: An Extremely Concise Praise of the Twenty-One Tārās
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:11:47.466033
  last_modified_at: 2022-03-01 02:11:47.466039
