id: A6C360E5C
title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord Atiśa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:11:47.468099
  last_modified_at: 2022-03-01 02:11:47.468103
