id: A6C360E5C
title: Light Offering Prayer
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:11:47.469420
  last_modified_at: 2022-03-01 02:11:47.469423
